services:
  - type: web
    name: betwinner-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: FOOTBALL_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: PORT
        value: 8080
      - key: WEBHOOK_URL
        sync: false
    autoDeploy: true
    numInstances: 1
    healthCheckPath: /
